### ISSUE TITLE
How to setup this source as a deb  package

### ISSUE THREAD

**Issue by munavver** [Beldex-Coin/beldex-multi-mn#2]
I want to setup an another master node in my existing master node VPS

**Comment by victor-tucci** [comment]
you can use this for creating deb package #3

**Comment by sanada08** [comment]
https://github.com/Beldex-Coin/beldex-multi-mn/edit/master/README.md#build-deb-package

**Comment by sanada08** [comment]
`git clone https://github.com/Beldex-Coin/beldex-multi-mn.git`
`sudo dpkg-deb --build --root-owner-group beldex-multi-mn`
`sudo dpkg -i beldex-multi-mn.deb`
